---
# Variables here are applicable to all splunk installs

# URL the the Splunk server rpm file, e.g. https://s3.amazonaws.com/yourbucket/splunk-6.1.3-220630-linux-2.6-x86_64.rpm
splunk_binary_url:

# The name of the Splunk rpm file, e.g. splunk-6.1.3-220630-linux-2.6-x86_64.rpm
splunk_binary_file:

# SHA256 of the Splunk rpm file above, e.g. c759e68dc39779b65fbd2ebc2b9e4d5509d1a1ca507f8bf4c2e489999df547da
splunk_binary_sha256sum:

# URL link Splunk's PGP  public key, e.g. https://s3.amazonaws.com/yourbucket/splunk-pgp-public.key
splunk_pgp_public_key:

# Domain name for all Splunk components, e.g. yourcompany.com
splunk_host_domain:

# IP address of the License Master
splunk_license_master:

# Your company name, e.g. acme
company:
